url: https://atamahjoubfar.github.io
baseurl: 
timezone: America/Los_Angeles

# Site settings
title: Ata Mahjoubfar
email: ata.m@ucla.edu
description: "This is Ata Mahjoubfar's personal website. He is a data capture and analytics expert."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ata Mahjoubfar
  pic: 1
  position: Data Scientist
  social:
    - title: twitter
      url: https://twitter.com/atamahjoubfar
    - title: facebook
      url: https://www.facebook.com/atamahjoubfar
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/atamahjoubfar
  - title: github
    url: https://github.com/atamahjoubfar
  - title: graduation-cap
    url: https://scholar.google.com/citations?user=-Hsvgm4AAAAJ&hl=en&oi=ao
  - title: twitter
    url: https://twitter.com/atamahjoubfar
  - title: facebook
    url: http://www.facebook.com/atamahjoubfar

# Postal address (add as many lines as necessary)
address:
  - line: 420 Westwood Plaza
  - line: Los Angeles, CA 90095

# Build settings
markdown: kramdown
permalink: pretty
